# -*- coding: utf-8 -*-
"""MNIST_Project_student.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SSuEUz0F1PKHREK7rU0Uff6fgHXNVYMi

"MNIST ("Modified National Institute of Standards and Technology")  is a large, open source database of handwritten digits, most often used in image processing softwares. It is the de facto “hello world” dataset of computer vision. Since its release in 1999, this classic dataset of handwritten images has served as the basis for benchmarking classification algorithms. As new machine learning techniques emerge, MNIST remains a reliable resource for researchers and learners alike."



[Read more.](https://www.kaggle.com/c/digit-recognizer)


<a title="By Josef Steppan [CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0)], from Wikimedia Commons" href="https://commons.wikimedia.org/wiki/File:MnistExamples.png"><img width="512" alt="MnistExamples" src="https://upload.wikimedia.org/wikipedia/commons/2/27/MnistExamples.png"/></a>

**Step 1 — Knowing The Dataset**
As we have mentioned previously, the most important step in machine learning is understanding your dataset and going through it thoroughly.

Luckily, for us PyTorch provides an easy implementation to download the cleaned and already prepared data, using a few lines of code. Before starting, we need to make all the necessary installation and imports of the relevant libraries.
"""

!pip install torch torchvision

#Import Libraries
import numpy as np
import torch
import torchvision
import matplotlib.pyplot as plt
from time import time
from torchvision import datasets, transforms
from torch import nn, optim
import torch.nn.functional as F
from torch.utils.data import DataLoader

"""PyTorch has its own version of a numpy array called a **tensor**. All of the models and functions we apply on the data can only be done on tensor types meaning that our data will have to be converted into a tensor first.

**transforms.ToTensor()**: this function allows us to convert a numpy array into a tensor type.

Fortunately, Pytorch already contains several datasets that we can access.
"""

trainset = datasets.MNIST('train', download = True, train = True, transform = transforms.ToTensor())
testset = datasets.MNIST('test', download = True, train = False, transform = transforms.ToTensor())

# these datasets come from torchvision library with datasets

"""So now we have a complete training and testing dataset! We can take a look at how large both of these datasets are:"""

trainset

testset

"""We can see that there are a large number of datapoints in the training and testing set. Training the model is a process that takes many iterations, and on each iteration the error is calculated and weights/bias are adjusted accordingly.

So we can split both the training and testing set into smaller groups of data called **batches**. PyTorch offers function that allows us to easily separate our datasets into batches called **DataLoader**.
"""

trainloader = DataLoader(trainset, batch_size = 32, shuffle = True)
testloader = DataLoader(testset, batch_size = 32, shuffle = True)

"""**Step 2 — Knowing The Dataset Better**

To obtain a single batch from our DataLoader, we can call a Python function called **iter()** which will allow us to access each batch by calling **.next()**
"""

for images, labels in trainloader:
  print(images, labels)
  break

labels

"""Now let's see what the shapes of our images and labels are"""

# ask what they think each number means
print(images.shape) # what the printed numbers/array mean: 10 (first number) represents our batch size, 1 (second number) represents the channels each image has, and 28 by 28 (third and fourth number) represents the length and width of each image.
print(labels.shape) #  what the printed numbers/array mean: 10(first number) represents the batch size

"""Now let's plot and show what this image looks like:"""

plt.imshow(images[0].numpy().squeeze(), cmap = 'gray_r')
#actual image of image[0]

labels[0] #label of image[0]

"""Cool right! Let’s display some more images, this will give us a feel of how the dataset looks like."""



"""This will generate a grid of images in a random order. Now, it is time to get started by defining the neural network we will be using.

**Step 3 — Creating the Model**

Now let's create our model! Each layer of a network will be a called in a separate variable. The main tools we will use are:
- **nn.Conv2d()**: applies a convolution for the given inputs
- **nn.Linear()**: applies a linear summation for the given inputs
"""

#testingéchecking to see that the layers match up
conv1 = nn.Conv2d(in_channels = 1, out_channels = 5, kernel_size = 3) #greyscale has a channel of 1, RGB has a channel of 3
conv2 = nn.Conv2d(in_channels = 5, out_channels = 3, kernel_size = 4, stride = 2)
pool1 = nn.MaxPool2d(kernel_size = 2, stride = 2, padding=0) #pooling layer
#pool1 = nn.AdaptiveMaxPool2d((6,6)) #pooling layer
result = conv1(images)
print(result.shape) #tells us there is a batch of 20 and it returns 5 channels with a 26 by 26 shape
result = conv2(result)
print(result.shape) #tells us there is a batch of 20 and it returns 3 channels with a 12 by 12 shape
#convolution.shape = [batch, # of matrices/channels ,matrix size, matrix size]
result = pool1(result)
result.shape

#6

#https://dingyan89.medium.com/calculating-parameters-of-convolutional-and-fully-connected-layers-with-keras-186590df36c6#:~:text=Followed%20by%20a%20max%2Dpooling%20layer%2C%20the%20method%20of%20calculating,)%2F2%20%2B1%20%3D%2014.

result.flatten(start_dim = 1).shape
#what does flatten do: result returns 3 matrices that are 12 by 12. flatten flattens the three 2D - matrices into a 1D matrix
#therefore [20 batches, 3*12*12 = 432]
#flattened convolution.shape = [batch, multiplied matrix sizes]

result = result.flatten(start_dim = 1)
linear1 = nn.Linear(3 * 12 * 12, 10) #output = 10 because there are 10 possible numbers from 0 to 9

print(linear1(result))

"""Creating the layers is not enough to complete the network. We also have to set our activation functions as well as determine our output from the model. The main ones that we will use in this example are:
- **Rectified Linear Unit**
- **Softmax**

Now that we have all of the parts of our network we can combine everything together.
"""

for images, labels in trainloader:
  x = conv1(images)
  x = conv2(x)
  x = x.flatten(start_dim = 1)
  x = linear1(x)
  x = F.softmax(x, dim = 1)
  print(x.shape)

  break

"""A standard coding practice when it comes to making neural networks is by creating a new **class** to represent our model."""

class MyModel(nn.Module):
  def __init__(self):
    #fill out
    super(MyModel, self).__init__()
    self.conv1 = nn.Conv2d(in_channels = 1, out_channels = 5, kernel_size = 3)
    #input is 1 28 by 28 matrix
    #output is 5 26 by 26 matrices - - based on convolution math/process/hyperparameters
    self.conv2 = nn.Conv2d(in_channels = 5, out_channels = 3, kernel_size = 4, stride = 2)
    #input is 5 26 by 26 matrices
    #output is 3 12 by 12 matrices  - based on convolution math/process/hyperparameters
    self.pool1 = nn.MaxPool2d(kernel_size = 2, stride = 2, padding=0)
    #input is 3 12 by 12 matices
    #output is 3 6 by 6 matrices
    #self.linear1 = nn.Linear(3 * 6 * 6, 1000)
    self.linear1 = nn.LazyLinear(1000)
    #input is 3*12*12 = 432 because the convolutional layer before outputs/returns 3 12 by 12 matrices and passes it into linear 1
    # 432 is represented in the 1D shape. the (conv2) output's 1D shape will be [batch, 3*12*12 = 432]. The 1D shape is seen by typing
    self.linear2 = nn.Linear(1000, 500)
    self.linear3 = nn.Linear(500, 250)
    self.linear4 = nn.Linear(250, 125)
    self.linear5 = nn.Linear(125, 10)
    # output is 10 bc it will return 10 values, corresponding to the 10 possible numbers/outputs (from 0 to 9)
    #self.dropout = nn.Dropout(0.2) #dropout is only used during training not evaluation


  def forward(self, images):
    x = self.conv1(images)
    x = self.conv2(x)
    x = self.pool1(x)
    x = x.flatten(start_dim = 1)
    x = torch.relu(self.linear1(x))
    #x = self.dropout(x)
    x = torch.relu(self.linear2(x))
    #x = self.dropout(x)
    x = torch.relu(self.linear3(x))
    #x = self.dropout(x)
    x = torch.relu(self.linear4(x))
    #x = self.dropout(x)
    x = self.linear5(x) #will return 10 values, corresponding to the 10 possible numbers/outputs (from 0 to 9)
    #x = self.dropout(x)
    x = F.softmax(x, dim = 1) #will return 10 probabilties, corresponding to the probabilities of each number
    # when it comes to activation functions that return probabilities: Sigmoid is used for binary classification methods where we only have 2 classes, while SoftMax applies to multiclass problems
    return x

## set hyperparameters, create model instance, loss function and optimizer
model = MyModel()
loss_function = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 0.0001)
#ADAM is what we usually use as an optimizer instead of SGD

images.shape

epochs = 10
all_train_loss = []
average_epoch_loss = []
y_pred_compare = []
y_pred_list = []
y_true_list = []

for epoch in range(epochs):
  print('EPOCH')
  epoch_loss = []
  for images, labels in trainloader:
    ##forward propogation##
    y_hat = model(images) #returns an array/tensor of ten probabilites. one for each possible number from 0 to 9.

    y_pred = torch.argmax(y_hat, dim = 1) #returns the index of the largest element in y_hat

    y_pred_compare = list(zip(y_pred.tolist(), labels.tolist()))

    y_pred_list.append(y_pred.tolist())
    y_true_list.append(labels.tolist())

    loss = loss_function(y_hat, labels)

    ##backward propogation##
    loss.backward() #calculating gradient
    optimizer.step() #taking the step, changing weights and so on according to gradient
    optimizer.zero_grad()#resetting gradient and step for the next iteration. sets to zero to be recalulated next turn.


    epoch_loss.append(loss.detach().item())
    all_train_loss.append(loss.detach().item())


  #print("Average Cross Entropy Loss" + str( sum(epoch_loss)/len(epoch_loss))))

  average_epoch_loss.append(sum(epoch_loss)/len(epoch_loss))

#turning y_true and y_pred lists into one long list instead of a list of bacthes(lists)
#unnesting the lists
y_true_list = sum(y_true_list, [])

y_pred_list = sum(y_pred_list, [])

print(y_pred_list)
print(y_true_list)

"""Let's take a quick look at what the output from this looks like:"""

print(average_epoch_loss)

print(all_train_loss)

print(y_pred_compare)

import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(10, 6))

n = 47 # Plot every 47th element
ax.plot(all_train_loss[::n], marker='o', markersize=3)
ax.set_xlabel('Iterations')
ax.set_ylabel('Loss')
ax.set_title('Training Loss over Time: Plotted At Every 47th Iteration')

plt.show()
#plotting without including every single datapoint to avoid overcrowding #excluding datapoints are regular intervals

from google.colab import drive
drive.mount('/content/drive')

import os
model_path = "/content/drive/MyDrive/UofT Computer Vision"
print("data_path:", model_path)
files = os.listdir(model_path)  # Get all the files in that directory
print(f"Files in current directory '{model_path}': {files}")

#saving model

model_name = 'number_predict11.pth'

PATH = model_path + "/" + model_name

torch.save(model.state_dict(), PATH)
print(f"Saved model: {model_name}")

#loading model
import torch
import torch.nn as nn
model_path = "/content/drive/MyDrive/UofT Computer Vision"
model_name = 'number_predict11.pth'
PATH = model_path + "/" + model_name
model = MyModel()
model.load_state_dict(torch.load(PATH)) #loading named model from drive
model.eval() #lets model know that its evaluating and so turns off dropout

Y_TRUE = []
Y_PRED = []

for images, labels in testloader:
  y_hat = model(images)
  y_pred = torch.argmax(y_hat, dim = 1)
  print(type(y_pred))
  print(y_pred.tolist())
  print(labels.tolist())
  print('\n')
  Y_TRUE.append(labels.tolist())
  Y_PRED.append(y_pred.tolist())

Y_TRUE = sum(Y_TRUE, [])

Y_PRED = sum(Y_PRED, [])

print(Y_PRED)
print(Y_TRUE)

#unnesting the list

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_TRUE, Y_PRED, labels=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

fig, ax = plt.subplots(figsize=(5, 5))
ax.imshow(cm, cmap=plt.cm.Blues)

class_names = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
tick_marks = np.arange(len(class_names))
plt.xticks(tick_marks, class_names, rotation=45)
plt.yticks(tick_marks, class_names)

thresh = cm.max() / 2.
for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        ax.text(j, i, format(cm[i, j], 'd'), ha="center", va="center", color="white" if cm[i, j] > thresh else "black")

plt.tight_layout()
plt.ylabel('True label')
plt.xlabel('Predicted label')
plt.title('Confusion Matrix')

plt.show()

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(Y_TRUE, Y_PRED)))

print('Micro Precision: {:.2f}'.format(precision_score(Y_TRUE, Y_PRED, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(Y_TRUE, Y_PRED, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(Y_TRUE, Y_PRED, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(Y_TRUE, Y_PRED, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(Y_TRUE, Y_PRED, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(Y_TRUE, Y_PRED, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(Y_TRUE, Y_PRED, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(Y_TRUE, Y_PRED, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(Y_TRUE, Y_PRED, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(Y_TRUE, Y_PRED, target_names=['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']))


#https://towardsdatascience.com/confusion-matrix-for-your-multi-class-machine-learning-model-ff9aa3bf7826

#Support is the number of actual occurrences of the class in the specified dataset. Imbalanced support in the training data may indicate structural weaknesses in the reported scores of the classifier and could indicate the need for stratified sampling or rebalancing.

import pickle

model_name = "number_predict11_1"
with open("/content/drive/MyDrive/UofT Computer Vision" + "/" + model_name +'.pkl', 'wb') as f:
    pickle.dump(model, f)

"""Since we used the softmax function which returns the probabilities, we can take the maximum probability from each row in our output and use that as the predicted number that our model returns for a specific image."""

y = model(testloader[])

labels

"""So now we have our neural network model created, we have to give it a way of learning. To do this we have to several more things:
- **Loss Function**
- **Optimizer**
- **Hyperparameters**
"""



def get_accuracy(output, labels, batch_size):
  diff = output - labels
  wrong_labels = np.count_nonzero(diff)
  accuracy = (batch_size - wrong_labels)/batch_size * 100
  print('Accuracy is: ', accuracy, '%')
  return None


def get_correct(output, labels, batch_size):
  diff = output - labels
  wrong_labels = np.count_nonzero(diff)
  return batch_size - wrong_labels

"""Now let's put everything together and let our neural network learn!"""



"""**EXCERCISE 1**
Test your model on the testing set and obtain the accuracy!
"""

class MyModel(nn.Module):
  def __init__(self):
    #fill out
    super(MyModel, self).__init__()
    self.conv1 = nn.Conv2d(in_channels = 1, out_channels = 5, kernel_size = 3)
    #input is 1 28 by 28 matrix
    #output is 5 26 by 26 matrices - - based on convolution math/process/hyperparameters
    self.conv2 = nn.Conv2d(in_channels = 5, out_channels = 3, kernel_size = 4, stride = 2)
    #input is 5 26 by 26 matrices
    #output is 3 12 by 12 matrices  - based on convolution math/process/hyperparameters
    self.pool1 = nn.MaxPool2d(kernel_size = 2, stride = 2, padding=0)
    #input is 3 12 by 12 matices
    #output is 3 6 by 6 matrices
    self.linear1 = nn.Linear(3 * 6 * 6, 1000)
    #input is 3*12*12 = 432 because the convolutional layer before outputs/returns 3 12 by 12 matrices and passes it into linear 1
    # 432 is represented in the 1D shape. the (conv2) output's 1D shape will be [batch, 3*12*12 = 432]. The 1D shape is seen by typing
    self.linear2 = nn.Linear(1000, 500)
    self.linear3 = nn.Linear(500, 250)
    self.linear4 = nn.Linear(250, 125)
    self.linear5 = nn.Linear(125, 10)
    # output is 10 bc it will return 10 values, corresponding to the 10 possible numbers/outputs (from 0 to 9)
    self.dropout = nn.Dropout(0.2) #dropout is only used during training not evaluation

  def forward(self, images):
    x = self.conv1(images)
    x = self.conv2(x)
    x = self.pool1(x)
    x = x.flatten(start_dim = 1)
    x = self.linear1(x)
    x = self.dropout(x)
    x = self.linear2(x)
    x = self.dropout(x)
    x = self.linear3(x)
    x = self.dropout(x)
    x = self.linear4(x)
    x = self.dropout(x)
    x = self.linear5(x) #will return 10 values, corresponding to the 10 possible numbers/outputs (from 0 to 9)
    x = self.dropout(x)
    x = F.softmax(x, dim = 1) #will return 10 probabilties, corresponding to the probabilities of each number
    return x

  def get_accuracy(output, labels, batch_size):
    diff = output - labels
    wrong_labels = np.count_nonzero(diff)
    accuracy = (batch_size - wrong_labels)/batch_size * 100
    print('Accuracy is: ', accuracy, '%')
    return None


  def get_correct(output, labels, batch_size):
    diff = output - labels
    wrong_labels = np.count_nonzero(diff)
    return batch_size - wrong_labels

"""Congratulations, you just made your first image classification neural network :)
The next step is to tune the hyperparameters and play around with the overall network to find the combination that will give the best model.
"""